### ISSUE TITLE
variables with _

### ISSUE THREAD

**Issue by meiremans** [aviaviavi/curl-runnings#42]
Hi

I cannot access a response with an underscore. I have as a response
[{
"_id" :"XXXXX",
"someElse": "YYYY"}]

$<RESPONSE[0][0].someElse> works, $<RESPONSE[0][0]._id> doesn't.

**Comment by aviaviavi** [comment]
Good catch, this should be an easy fix

**Comment by aviaviavi** [comment]
Fixed with #43

**Comment by aviaviavi** [comment]
@meiremans please let me know whether this fix works for you. You'll want to be on version 0.11.1
