### ISSUE TITLE
var name

### ISSUE THREAD

**Issue by Rashadse** [aviaviavi/curl-runnings#45]
https://github.com/aviaviavi/curl-runnings/blob/9f08b25232c28c437454614c989659602cbfa18e/examples/importable.yaml#L4

Isn't this supposed to be ping_path
because you are using ${ping_path} in the other example file.
If not, where are you using some_path ?

**Comment by aviaviavi** [comment]
Ah so what's here is actually correct, but perhaps the overlapping names is causing confusion. `${ping_path}` refers to an environment variable to be interpolated into your spec. 

`&ping ping` represents an anchor named `ping` which also evaluates to the string `ping`

You can see where we import this anchor here: 

https://github.com/aviaviavi/curl-runnings/blob/9f08b25232c28c437454614c989659602cbfa18e/examples/interpolation-spec.yaml#L69

the `*` denotes that we're using the anchor value from the line you referenced. Does that make sense?

**Comment by Rashadse** [comment]
Got it thanks!
