### ISSUE TITLE
concatinating urls with anchors

### ISSUE THREAD

**Issue by Rashadse** [aviaviavi/curl-runnings#47]
https://github.com/aviaviavi/curl-runnings/blob/9f08b25232c28c437454614c989659602cbfa18e/examples/interpolation-spec.yaml#L31

Hi, i am wondering if there is a way to get around using anchors in urls
right now this doesn't work:
- name: GET Latest Testresult
    url: http://host.com/test/*baseline

**Comment by aviaviavi** [comment]
Hi @Rashadse, unfortunately the functionality you're describing is not available in curl-runnings. Anchors are at the yaml level, which doesn't support anchor concatenation. Currently, by the time curl-runnings loads your yaml spec, the anchor information is gone.

If you want to have a bit more flexibility for general programming inside of your curl-runnings spec, one two immediate options:
- Inject baseline into an environment variable and concatenate that.
- Write your configuration in a configuration language like dhall (https://github.com/dhall-lang/dhall-lang), and generate the yaml from there. 

I'll think about ways we could support this behavior, there are a few options to get this implemented in curl-runnings.

**Comment by Rashadse** [comment]
Big thanks, please let me know if you implement this in curl-runnings.
