### ISSUE TITLE
logging summary of testcases

### ISSUE THREAD

**Issue by Rashadse** [aviaviavi/curl-runnings#53]
Hello again,

Is there a way to log to a file (JSON preferably)?
We need a summary of the test case results (along with the new timers) logged to a file in order to be visualized by another service.
It could be a very simple JSON with a 
key: testresult and the value: [PASS] GET Latest Testresult (0.02 seconds)
it would be much nice if it was in lists though:

```
[
	{
		"case_name": "Get all",
		"verdict": "fail",
		"time": "0.50"
	},
	{
		"case_name": "Post testresult",
		"verdict": "pass",
		"time": "0.06"
	}
]
```

**Comment by aviaviavi** [comment]
Hey @Rashadse. That functionality doesn't currently exist in curl-runnings either, but it could be added.

**Comment by aviaviavi** [comment]
Just curious, are you trying to hook this up to your own internal dashboards, or another external tool? We've had requests for TAP (#13) and Report Portal (#41)

**Comment by Rashadse** [comment]
You could say it is technically internal tool. But it is our own elastic search cluster that is visualised by kibana.
Logging to the json file would save us a lot of parsing work with regx or grok.

**Comment by aviaviavi** [comment]
Got it, thanks for that info
