### ISSUE TITLE
Possibility of using this on Windows

### ISSUE THREAD

**Issue by humbienri** [aviaviavi/curl-runnings#54]
This tool looks like cool and useful. However, I wonder if there is any interest or plans to port it over to Windows?

**Comment by aviaviavi** [comment]
Hi @humbienri, glad you think so! This is the first request for Windows support, so it's not currently planned. I can look into it if there is more interest. Porting it should be fairly straightforward.

If you'd like to use it before it's ported, the README has instructions for using curl-runnings inside of docker.

**Comment by humbienri** [comment]
Interesting! I'll have a read....now I feel dumb.  I just enabled WSL and installed Debian Linux on my weak laptop just to be able to play with curl-runnings.

I'll give the docker option a try though.

Thank you @aviaviavi

**Comment by aviaviavi** [comment]
No dumb questions here. :) You're very welcome! 

I'll leave this open to track windows support if any updates arise.

**Comment by humbienri** [comment]
After going the docker way, I am getting an error when trying to run the test, 
```ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp```

**Comment by aviaviavi** [comment]
can you try adding `sudo apt install -y netbase` to your Dockerfile and try again?

**Comment by humbienri** [comment]
Yay! We have a failing test! At least it's working :)

So I had to modify the dockerfile as such:
```
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y curl && \
  apt-get install -y netbase
```
There was complaints about `sudo` being an unknown package or some'n like that.

Thank you @aviaviavi , now on to make a test pass and read up on your examples.

**Comment by aviaviavi** [comment]
Right on, happy testing!

**Comment by humbienri** [comment]
Thanks @aviaviavi . Do you want me to close this issue or leave it open to see if others express any interest in this?

**Comment by aviaviavi** [comment]
No problem! I just opened a fresh one to track Windows support, just since this thread had some other stuff going on.
