### ISSUE TITLE
Assumes responses will be json?

### ISSUE THREAD

**Issue by humbienri** [aviaviavi/curl-runnings#59]
Hello @aviaviavi ,

Does this tool assume, per the matchers, that the response will be of json format? i.e this will only work for API calls that return json?

Again, thank you sir.

**Comment by humbienri** [comment]
Disregard.  I see that one of the comments in the examples folder does reference json payload so I assume that means yes, json response bodies only.

**Comment by aviaviavi** [comment]
Glad you found the answer. It does indeed assume JSON payloads right now. If you need something different, happy to discuss it! While JSON API's were the original reason I wrote the tool, we can definitely work towards something more general over time.

**Comment by humbienri** [comment]
Nah, that's fine @aviaviavi.  I know you are doing this on your own time.  I do thank you!

**Comment by aviaviavi** [comment]
You're welcome!

I'll close this then. I actually am curious about what formats you were looking for, there may be others who face a similar need down the road.
