### ISSUE TITLE
JSON request payloads should allow any json value type

### ISSUE THREAD

**Issue by aviaviavi** [aviaviavi/curl-runnings#61]
Currently, `payload` can only be an object, but it should really allow any JSON value. 

cc @rashadse

**Comment by aviaviavi** [comment]
@Rashadse - I misread the code. You actually can get an array request body like so: 

```
payload: {"bodyType": "json", "content": ["key1", "value1"]}
```

**Comment by JonathanFlod** [comment]
Hi, I'm trying to use this feature but I'm not sure I understand how to implement it. Right now we're specifying our tests in test.yml and I was planning to add an yml-array which didn't work out. Should I write all the tests as json or is it a way to combine them?

**Comment by aviaviavi** [comment]
@JonathanFlod 

Sorry about that! My example above was incorrect and has been updated (specifically, the key for specifying the request body is still "requestData". I had mistakenly written "payload")

Let me know if you're still having trouble

**Comment by JonathanFlod** [comment]
Thanks alot, worked out just fine :)
